# Generated by Django 5.0.4 on 2026-04-19 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(default='nowpayments', max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nowpayments_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('product_id', models.CharField(choices=[('subscription_weekly', 'Weekly Subscription'), ('subscription_monthly', 'Monthly Subscription'), ('subscription_vip', 'VIP Subscription'), ('token_one_time', 'One Time Access'), ('token_daily', 'Daily Access'), ('token_weekly', 'Weekly Token')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
